name: Trigger Jenkins Job
# comment added
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  trigger-jenkins:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
        run: |
          Invoke-WebRequest -Uri "${{ secrets.JENKINS_URL }}/job/firstjob/build" -Method Post -Credential (New-Object PSCredential("${{ secrets.JENKINS_USER }}", (ConvertTo-SecureString "${{ secrets.JENKINS_TOKEN }}" -AsPlainText -Force)))
