name: Trigger Jenkins Job
# comment
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Check connectivity to Jenkins
        run: |
          ping -c 4 http://localhost:8080/
          curl -v http://localhost:8080/

