name: Trigger Jenkins Job
# comment added
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  trigger-jenkins:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_USER : ${{ secrets.JENKINS_USER }}
        run: |
          curl -u $JENKINS_USER:$JENKINS_API_TOKEN -X POST "$JENKINS_URL/job/firstjob/build"

